### ISSUE TITLE
Properly support schemaless reading and writing

### ISSUE THREAD

**Issue by flavray** [flavray/pyo3avro-rs#16]
Schemaless reading and writing is what is used the most when using Avro as a format for Kafka messages. Benchmarks for avro-rs and [pyavro-rs](https://github.com/flavray/pyavro-rs/blob/master/examples/benchmark.py).

Support is already almost complete, here are some of the things that need to be done:

- Rename {{AvroSchema}} -> {{Schema}} in the Python interface
- Do not panic upon bogus data (no {{unwrap}})

**Comment by poros** [comment]
If we returned a custom error type instead of `Error` in `avro-rs`, we could write a `convert::From` and then just use the `?` instead of unwrap https://github.com/PyO3/pyo3/blob/master/guide/src/exception.md#handle-rust-errors

But since I don't feel like waiting for https://github.com/flavray/avro-rs/issues/82, I'll create Errors manually.
